language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
  api_key:
    secure: QR676tNZNHMSi8W3nTgjz2WDTdZmHu7poJKPR3NRkcKYgthPabfZd8Xrzj2iuJ7Z7Z6Ym8K0C4lF5tBRfcsJrLOIq/fXYRfkertgKXnpB5lkSq72/c8mMe+x1VJAAcErHUggv+AZMp3cGx/fzIwSukS5KxzPy73RGnsMvCujWpaBefYxMxNiHSuxj+YVy6xwS2Arl9nlH5o74C8afxQBB6BKDLi9/ZUzDgTakwkVzRQmeugBzTSHBeHVDr2c5EeIYRAOUxDdcSjWvhbI0G+37e6VDa/QFmvCjQvkWvT0xc24Fjt8sZ8S8yJxX2xk80KKI9NMr1HZf1Xo5C9Dh8x7spwjtv1cvAvCVu0JLXMf/IwjxmnQqhiK5Xuh6eWQ9absK3Vd3zTg96vR4Iht9gWYNKPgduFKrH3yku+uv74UQreJuHaUHL9IVDTfp92nQCjgWJxHB41wskYzk/lo5RL2/iYz2wezHDUDXK5WKhZ/Y/9DBuzzHzV9UKtibuKqnsXKXaiVMbhBy/ihIaqtoiSW0mdhKfQ8oS8WRHZg7uiN1A5Jf0wDVsiWR4GFGSGKDYC0UtlP/OkFTw9CnDg8tvKZQ7y5JZ7Q3Oc+lfQUMnhd7dVPDgE0eoTKAACkacx6onoy7n2kolxVcUET+e6C4uL3k68s13u8LrQRxz5/vwn3Chk=
