language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
