language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
  api_key:
    secure: cjA13neS/VyZQUnqVDRsp+POv4pxYbONPNWbF+bc4Gu0AQhgbzMGUR5br3XQh8vPqhFQEGnxyS31CMsypVxTG0lHWehrwObTMI10wkAyq/ItKQkgUKxia1hZf/ND0TcYz3KWFs7x0+BH/VEXC0LpUguoyzKOMLF+6/FmvG5d2x/yb6ic7kHEZ7L9xWT1mxiCbZcAuF8jLY+RF1bzASdl+i7fZDxLdY0b+YETzgQFS8ZDwHEx4q/jMJOx2sC4dRAaaoquQ/tqJ6HCL1S/S5uQyxxni9XMBkQ9HpTHaLnbZ4DsYR9TgkegN8A8aQlkB5qiwIcHip9KFbYByheLnRJnUvsgjXsdDhYmr+SDGpjIYlOhfKwBZMjj7M7oBy3ONTubp5CcfATwPM50wzd5bniJ6qyZjtTZFVmkcddqLHntFypR+icB4XP52mvHSkK2f8d7A+9pqqzSWQSo3rU+PivQu001JxU7myuTvvSYAyG57kvbjcXAOoxQU+e1GHQox0H8c/UUz2pJGjjG+eshPwknqLTSaqZUsnv9oCmhqwbuvwAEDzU8kY8NTai9B5Wd1gy9mKf/Iu1RSqQvEI8vjeUm7VEotH46UavHQxfNSAR6+tUqwL7mJY3O+8fPYLhFge94aCZTyzTcVVSBWV99tYuEK6MgG8p8kxDnGuliMTZyC0w=
