language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: PTYOvfgk9BQe2+yIvyYkyTrxNbztOyzyIFVPv9mUj4s1df0tFocz0XluP81mqv+xdvHaBpJ13fAVzb2sUBjBrQ8jqJuiQhwH7vYUGj1+BvluvZBlwK4xar5wOjmt/kk2tJhuNzGGfLAJdf9KaaZ39UC3O1RvfXN8T5Ub64M7tSCIq3kwgD2co6kQ1dtWwJT+3W+5WmtCQBUMmemHUSehuAWxPuYo7oSNfxEzCpGW0paCEVlG3trG6zIcXwgdc+zmRsYjTVnUpefMxXXnqFvTES3owsHKW060mfH1Nas7t0E2ut+9sHHPFd650gvgN2rok967IKt8Wlm/ezqENmrP8ytYfD763WHJTeLuIbd49i++L3CDC1urnzATS96o+9lCl3adScw6RKFDvPGc8wPZs2gttsvhNx16YvS+DWVqkWrPv/g+jAHQ+kY6j0OsQBNvwYt4EEMLQFQln//Z2aiBinBXiZiMlAwvNncKNXq2A0f5w/gTXT5FvUzBItQjD3vqtyH0ddnhgR/Lf/T4S19v9UZBQJriBZ9WuP27OFOIJfW+b1m8J91XZQNLhP7TRw4sCKNDSqrqWTqTgNVDTmLkKbYywUnxFy0yj3MjSkpckzdYewrpHbfSFv7uid9y9NmY30zJ9tc3NaO1kmq7OixHhx4IlhlEQBkqhjkj2VKqslY=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
