language: node_js
node_js:
- node
services:
- mongodb
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: Z1J0cFvBiIweezIaZsfIEt+5S/tVzdQPy9cxvGRL9b2QoI6fSlzNG3n9uemQvNXItW48en+1C7cp4F1jF7fL47CGr/KnJBoEZ4JJ2tr3Sznhh2BO4yvo10Ocixz/PXgNhQ6uzQt6iL+N+9cHMZIQNrDu2zehgMokGneJwuP6cQbYfwFJ47zKTy/hf1lHwKzoYIDQm9aMI/IBBI69nIdGKdXVzPLVBQf5eaRWP9fu45PsePpPifuk2WCGUVcYgJDQDkANyXQHEolAhQ3OWYBHcznAWb3VEiBgRiJixzUIkNLtUbo3pspmqrD5vFTTjkAbxk9Y/fhvZ7hq+eOQAdWt0pCY66e3AHaFweljuWGReFtSMvXlrFxCFjsXPGlyxHJqMowiv8JC3h8faTwGHo2JzmFpCfJ3l4HFeENNFpN/Vx5zqujG2l4kMJ89GcnDtRkFHdFo++3SJuzVIKTwmGc5aSrLb//JqSmoKdFsrv1ytPNomEOlvppSS09kRFWZF7v7ZADHAlpaFz+d66xpPwPGyLUw3iX3l96PlKYGeld1Hss2LCrriZ9azflw80H33VZD6CbZl/h0njxrXPh2cG7v4qyt6rESvJ69GdkjnwkC9YoMq9oylt4HmqHk0GtpD2AiZwdOX5O+XRY6g0AmdORMp4eCWyuWtTOp9WwynavzwjU=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
